name: Build with ndk-build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Run ndk-build
        run: |
          ${{ steps.setup-ndk.outputs.ndk-path }}/ndk-build -C jni

      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: keybuster-binaries
          path: |
            libs/
            obj/local/*/keybuster*
